# Generated by Django 3.1 on 2020-09-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christopher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='map_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
