# Generated by Django 3.1 on 2020-10-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christopher', '0002_auto_20200927_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='icon_path',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='log_file_dir',
            field=models.CharField(max_length=128),
        ),
    ]
