# Generated by Django 3.1 on 2020-10-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christopher', '0003_auto_20201005_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='log_name',
            new_name='served_file_name',
        ),
        migrations.AddField(
            model_name='match',
            name='inner_log_name',
            field=models.CharField(default='log.jlog', max_length=128, unique=True),
        ),
    ]
