# Generated by Django 3.1 on 2020-10-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christopher', '0004_auto_20201007_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='inner_log_name',
            field=models.CharField(default='log.jlog', max_length=128),
        ),
    ]
